### PR TITLE
Feature sesion workflow 33

### PR DESCRIPTION
**Pull request by johnrosswvsu**
https://github.com/Luukyb/DrupalcampCebu2014/issues/33

Added workflow for session.
Adding field permissions to day and time
Adding editor and administrator roles.
Adding approval flag for session for admin and editor (flag module included.)

### CODE REVIEW

**Comment by Luukyb** [comment]
:+1: 
I'd like us to use secure permission module for the roles and permission, not features.
https://www.drupal.org/project/secure_permissions

**Comment by johnrosswvsu** [comment]
Removed permissions in feature and exported using secure_permissions.

Please check.

**Comment by Luukyb** [comment]
The role are still in features, is it normal ? We had this kind of issues last time with @mtem27 I think.
Have you tried rebuilding the site in your local ?
Also have you updated the view session ? Should be displayed only nodes that have been accepted.

**Comment by johnrosswvsu** [comment]
@Luukyb, the view sessions is still on hold, waiting for @marychris to commit. I will update the sponsors though.

**Comment by johnrosswvsu** [comment]
@Luukyb 
- Removed roles in features
- Updated views to make use of flag

Please check.

**Pull request merged**
